Check if stream exists before unsetting preferred URI
twilio/twilio-voice.js pull request #106
Opened 2022-08-18 11:48 UTC by SiimMardus

**Contributing to Twilio**

> All third party contributors acknowledge that any contributions they provide will be made under the same open source license that the open source project is provided under.

- [ ] I acknowledge that all my contributions will be made under the project's license.

## Pull Request Details

### JIRA link(s):

-

### Description

#95

maybeUnsetPreferredUri function was added in this commit:
https://github.com/twilio/twilio-voice.js/commit/b2b65437681ce6aa69870505a40d9f42323d7c9e

This caused unhandled error for some flows, such as when user
denies microphone access.

To fix this, we should check if the stream even exists before
attempting to calling `updatePreferredURI` on it.

## Burndown

### Before review
* [ ] Updated CHANGELOG.md if necessary
* [ ] Added unit tests if necessary
* [ ] Updated affected documentation
* [ ] Verified locally with `npm test`
* [ ] Manually sanity tested running locally
* [ ] Ready for review

### Before merge
* [ ] Got one or more +1s
* [ ] Squashed erroneous commits if necessary
* [ ] Re-tested if necessary

2022-08-18 12:01 UTC, SiimMardus commented
@mhuynh5757 @charliesantos @ryan-rowland Could anyone review this PR please 🙂 Currently when user denies media permissions, it causes an unhandled error from device, since Device tries to unset preferred URI for Stream when it is `null`.

Simply checking if Stream exists before doing it temporarily fixes the issue in this flow. I lack the knowledge whether or not the stream _should_ exist there at this point, but if it does, it's a different issue that could be looked into after this current fix is in place, as it's blocking us from migrating from V1 to V2.

2023-02-15 20:31 UTC, charliesantos requested changes
This is great @SiimMardus . Thank you for contributing. And apologies for responding too late. I left a comment. Please let me know what you think.

2023-02-15 20:31 UTC, charliesantos commented on lib/twilio/device.ts
> +      if (this._stream && this._activeCall === null && this._calls.length === 0) {
Can we please log a warning if stream is null? Maybe put this check at the top?
```js
    const maybeUnsetPreferredUri = () => {
      if (!this._stream) {
        return this._log.warn('UnsetPreferredUri called without a stream');
      }
      if (this._activeCall === null && this._calls.length === 0) {
        this._stream.updatePreferredURI(null);
      }
    };
```

2023-02-15 21:51 UTC, mhuynh5757 requested changes

2023-02-15 21:51 UTC, mhuynh5757 commented on package.json
> +    "@types/mime": "2.0.3",
Let's do a separate PR for this since we should also update our `package-lock.json`.

2023-02-17 15:31 UTC, ostap0207 commented
@mhuynh5757 Siim and I work together, I have opened another PR that only contains the fix, as changes in these PR are already in our master's fork https://github.com/twilio/twilio-voice.js/pull/143.

2023-02-17 18:03 UTC, charliesantos commented
Thanks for submitting @SiimMardus  . I resubmitted your PR here https://github.com/twilio/twilio-voice.js/pull/144 and added our original comments and also a changelog. I'll close this now.

2023-02-17 18:03 UTC, closed without merging