VBLOCKS-1301 Remove ws and xmlhttprequest dependencies.
twilio/twilio-voice.js pull request #170
Opened 2023-06-08 21:36 UTC by manjeshbhargav

**Contributing to Twilio**

> All third party contributors acknowledge that any contributions they provide will be made under the same open source license that the open source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

## Pull Request Details

### JIRA link(s):

- [VBLOCKS-1301](https://issues.corp.twilio.com/browse/VBLOCKS-1301)

### Description

* Remove `xmlhttprequest` package from dependency (use `fetch` instead).
* Move `ws` package to `devDependencies` (as it is required for unit tests).

## Burndown

### Before review
* [x] Updated CHANGELOG.md if necessary
* [ ] Added unit tests if necessary
* [ ] Updated affected documentation
* [x] Verified locally with `npm test`
* [x] Manually sanity tested running locally
* [x] Ready for review

### Before merge
* [ ] Got one or more +1s
* [ ] Squashed erroneous commits if necessary
* [ ] Re-tested if necessary

2023-06-08 21:42 UTC, charliesantos requested changes
I did a quick pass, here are my initial comments. I'll continue to review later.
- `ws` is used in [wstransport.ts](https://github.com/twilio/twilio-voice.js/blob/VBLOCKS-1301/remove-xmlhttprequest-ws/lib/twilio/wstransport.ts#L8). We should update this file so it uses the browser's default WebSocket class and verify it works on all supported browsers.
- build is failing due to the flaky test. please re-run the job

2023-06-14 20:47 UTC, charliesantos commented on lib/twilio/request.ts
> +  const fetchUrl = options.fetch || fetch;
```suggestion
```

2023-06-14 20:48 UTC, charliesantos commented on lib/twilio/request.ts
> +  fetchUrl(params.url, { body, headers, method })
```suggestion
  fetch(params.url, { body, headers, method })
```

2023-06-14 22:39 UTC, mhuynh5757 commented on tests/index.ts
It doesn't look like we use this file for network (e2e) tests, so we don't really need a real `WebSocket` implementation right? Should we think about just mocking the `WebSocket` object so we can drop the dependency entirely?

2023-06-14 23:20 UTC, manjeshbhargav commented on tests/index.ts
@mhuynh5757 We already mock the WebSocket for unit tests. Unfortunately the typescript compiler for mocha complains about not only the type definition, but also about the package itself. So, this is the best option as of now.

2023-06-15 20:20 UTC, merged