fix(audio): Persist enabled sounds state
twilio/twilio-voice.js pull request #179
Opened 2023-07-03 22:49 UTC by kamalbennani

**Contributing to Twilio**

> All third party contributors acknowledge that any contributions they provide will be made under the same open source license that the open source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

## Pull Request Details

### JIRA link(s):

- [CLIENT-0000](https://issues.corp.twilio.com/browse/CLIENT-0000)

### Description

This PR ensures that the enabled state persist during the lifetime of a Device instance.

Fixes #178 

## Burndown

### Before review
* [ ] Updated CHANGELOG.md if necessary
* [x] Added unit tests if necessary
* [ ] Updated affected documentation
* [x] Verified locally with `npm test`
* [x] Manually sanity tested running locally
* [x] Ready for review

### Before merge
* [ ] Got one or more +1s
* [ ] Squashed erroneous commits if necessary
* [ ] Re-tested if necessary

2023-07-04 04:09 UTC, charliesantos requested changes
Looks great @kamalbennani ! I left one comment.

2023-07-04 15:30 UTC, kamalbennani commented on lib/twilio/audiohelper.ts
> +  get enabledSounds(): Record<Device.ToggleableSound, boolean> { return this._enabledSounds; }
Thanks for the suggestion.
I cannot rename it using the underscore as it will conflict with the variable name.
What do you suggest here?

2023-07-05 17:43 UTC, charliesantos commented on lib/twilio/audiohelper.ts
> +  get enabledSounds(): Record<Device.ToggleableSound, boolean> { return this._enabledSounds; }
@kamalbennani you can make the getter a function
```ts
  /**
   * @private
   */
  _getEnabledSounds(): Record<Device.ToggleableSound, boolean> {
    return this._enabledSounds;
  }
```

2023-07-05 22:08 UTC, charliesantos approved these changes
Thanks @kamalbennani this looks good!

2023-07-05 22:08 UTC, merged