[VBLOCKS-2716] Chrome extension e2e
twilio/twilio-voice.js pull request #277
Opened 2024-06-27 21:15 UTC by kpchoy

**Contributing to Twilio**

> All third party contributors acknowledge that any contributions they provide will be made under the same open source license that the open source project is provided under.

- [ ] I acknowledge that all my contributions will be made under the project's license.

## Pull Request Details

### JIRA link(s):

- [CLIENT-0000](https://issues.corp.twilio.com/browse/CLIENT-0000)

### Description

A description of what this PR does.

## Burndown

### Before review
* [ ] Updated CHANGELOG.md if necessary
* [ ] Added unit tests if necessary
* [ ] Updated affected documentation
* [ ] Verified locally with `npm test`
* [ ] Manually sanity tested running locally
* [ ] Ready for review

### Before merge
* [ ] Got one or more +1s
* [ ] Squashed erroneous commits if necessary
* [ ] Re-tested if necessary

2024-07-03 15:42 UTC, charliesantos requested changes

2024-07-03 15:42 UTC, charliesantos commented on tests/extension/app/twilio.js
This file needs to be a symlink to `dist/twilio.js`.

2024-07-03 15:42 UTC, charliesantos commented on tests/extension/package.json
Let's delete this file and merge the scripts, dependencies, and devDependencies to the root package.json.

2024-07-04 00:11 UTC, kpchoy commented
One thing to note @charliesantos is that Twilio@4.22.0 breaks in the integration tests, so I left current 3.x version in root. However, the chrome extension package.json uses Twilio@4.22.0

2024-07-08 23:38 UTC, charliesantos approved these changes

2024-07-08 23:59 UTC, merged